-- Test of Lua calling BDOS
print("Calling BDOS...");
BdosCall(2, string.byte("H"))
BdosCall(2, string.byte("e"))
BdosCall(2, string.byte("l"))
BdosCall(2, string.byte("l"))
BdosCall(2, string.byte("o"))
BdosCall(2, string.byte(" "))
BdosCall(2, string.byte("W"))
BdosCall(2, string.byte("o"))
BdosCall(2, string.byte("r"))
BdosCall(2, string.byte("l"))
BdosCall(2, string.byte("d"))
BdosCall(2, string.byte("!"))
--